log_dir: "emostargan/esdall_emotion_self_coding_stopLeakage_round3_epochs200/"
device: "cuda"
epochs: 200
save_freq: 1
batch_size: 256
pretrained_model: ""
load_only_params: false
fp16_run: true
domain: "emotions"

train_data: "Dataset/Emotional Speech Dataset (ESD)/English_sub_set/train_list.txt"
val_data: "Dataset/Emotional Speech Dataset (ESD)/English_sub_set/val_list.txt"

first_stage_model_path: "/project/sghosh/code/emostargan/Utils/emotion_encoder/emotion_style_encoder_pretrained_first_stage.pth"
optimizer_params:
  lr: 0.0001

loss_params:
  lambda_coding_loss: 10.0
